INFO     [🔧TEST CONFIG]:conftest.py:87 Loading test configuration
INFO     [🔧TEST CONFIG]:conftest.py:396 Navigating to: https://console.dev.apolo.us/
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/api/v1/config
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"authorized": false, "auth_url": "https://auth.dev.apolo.us/authorize", "token_url": "https://auth.dev.apolo.us/oauth/token", "logout_url": "https://auth.dev.apolo.us/v2/logout?returnTo=https://console.dev.apolo.us", "client_id": "q3I0OzzGnTDkhRmpeJ7WWgaTCucmVxTL", "audience": "https://api.dev.apolo.us", "callback_urls": ["http://127.0.0.1:54540", "http://127.0.0.1:54541", "http://127.0.0.1:54542"], "headless_callback_url": "https://api.dev.apolo.us/oauth/show-code", "success_redirect_url": "https://api.dev.apolo.us/oauth/login"}
INFO     [🔧TEST CONFIG]:conftest.py:93 Creating data manager
INFO     [🔧TEST CONFIG]:conftest.py:123 Creating users manager
INFO     [🔧TEST CONFIG]:conftest.py:109 Creating API helper
INFO     [🔧TEST CONFIG]:conftest.py:117 Creating Apolo CLI instance
INFO     [👤UsersManager]:users_manager.py:73 Setting main user to UserData(email='regression-67p1t5y1i1@apolo.us', username='regression-67p1t5y1i1', password='@T*wc2Y&l#Yf')
INFO     [👤UsersManager]:users_manager.py:82 Setting second user to None
INFO     [👤UsersManager]:users_manager.py:91 Setting third user to None
INFO     [📘TEST_INFO]:reporting.py:86 ------------------------------------------------------------
INFO     [📘TEST_INFO]:reporting.py:87 📝 TEST started: Import PostgreSQL app config via UI
INFO     [📘TEST_INFO]:reporting.py:88 ------------------------------------------------------------
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Login via UI
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Click login button
INFO     [🎭 Playwright]:base_page.py:16 <AuthPage>: Click log in button
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Click login button
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_click_login_button_success_19b5d9.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Enter email
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Enter regression-67p1t5y1i1@apolo.us email
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Enter email
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_enter_email_success_5c86c5.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Enter password
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Enter ********* password
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Enter password
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_enter_password_success_c6d749.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Click Continue button
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Click continue button
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/api/v1/config
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"authorized": true, "orgs": [{"name": "regression-org-0myyg5phwb91", "role": "admin"}], "clusters": [{"name": "default", "registry_url": "https://registry.api.dev.apolo.us", "storage_url": "https://api.dev.apolo.us/api/v1/storage", "monitoring_url": "https://monitoring.api.dev.apolo.us/api/v1/jobs", "secrets_url": "https://api.dev.apolo.us/api/v1/secrets", "metrics_url": "https://grafana.dev.apolo.us", "disks_url": "https://api.dev.apolo.us/api/v1/disk", "buckets_url": "https://api.dev.apolo.us/api/v1/buckets", "resource_pool_types": [{"name": "a2-highgpu-1g", "min_size": 0, "max_size": 10, "cpu": 12.0, "available_cpu": 11.101, "memory": 89629032448, "available_memory": 80898240256, "disk_size": 523982073856, "available_disk_size": 364209683290, "nvidia_gpu": {"count": 1, "model": "NVIDIA-A100-SXM4-40GB", "memory": 42949672960}}, {"name": "a2-highgpu-2g", "min_size": 0, "max_size": 3, "cpu": 24.0, "available_cpu": 23.73, "memory": 179367243776, "available_memory": 168094003200, "disk_size": 523982073856, "available_disk_size": 364209683290, "nvidia_gpu": {"count": 1, "model": "NVIDIA-A100-SXM4-40GB", "memory": 42949672960}}, {"name": "a3-highgpu-1g", "min_size": 0, "max_size": 1, "cpu": 26.0, "available_cpu": 25, "memory": 234000000000, "available_memory": 210600000000, "disk_size": 750000000000, "available_disk_size": 750000000000, "nvidia_gpu": {"count": 1, "model": "NVIDIA-A100-SXM4-80GB", "memory": 85899345920}}, {"name": "default", "min_size": 1, "max_size": 10, "cpu": 4.0, "available_cpu": 3.021, "memory": 16776040448, "available_memory": 12439842560, "disk_size": 101203873792, "available_disk_size": 47060071478}, {"name": "g2-standard-4", "min_size": 0, "max_size": 10, "cpu": 4.0, "available_cpu": 3.121, "memory": 16776052736, "available_memory": 12490174208, "disk_size": 312594247680, "available_disk_size": 173960640047, "nvidia_gpu": {"count": 1, "model": "NVIDIA-L4", "memory": 24152899584}}], "resource_presets": [{"name": "cpu-micro", "credits_per_hour": 
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/admin/v1/invites/incoming
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
[]
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/admin/v1/orgs/regression-org-0myyg5phwb91
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"name": "regression-org-0myyg5phwb91", "balance": {"credits": "499.8499969280000000000000000", "spent_credits": "0.1500030720000000000000000000"}, "user_default_credits": null, "notification_intervals": {"balance_projection_seconds": [604800, 259200, 86400], "balance_amount": [0], "balance_depletion_seconds": [86400, 604800]}}
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-0myyg5phwb91&project=regression-proj-9gs75udp89&cluster=default&size=100
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"items":[{"id":"c0472191-d551-4c81-b880-27f8a05dd285","name":"regression-org-0myyg5phwb91-regression-proj--c0472191","created_at":"2025-10-11T01:56:35.783085Z","updated_at":"2025-10-11T01:57:37.485630Z","creator":"regression-67p1t5y1i1","display_name":"Shell-regression-cgcnxukj","template_name":"shell","template_version":"v25.8.0","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"healthy","app_type":"mlops","endpoints":[{"path":"$.app_url.external_url.host","friendly_name":"App Url","url":"https://shell--c0472191d5514c81b88027f8a05dd285.apps.dev.apolo.us"}]},{"id":"b5d9777f-9043-4a25-83ee-c8be2c336f84","name":"regression-org-0myyg5phwb91-regression-proj--b5d9777f","created_at":"2025-10-11T01:50:52.179617Z","updated_at":"2025-10-11T01:59:08.472328Z","creator":"regression-67p1t5y1i1","display_name":"PostgreSQL-regression-jym8a6mh","template_name":"postgres","template_version":"v25.9.1","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"uninstalled","app_type":"workflow","endpoints":[]}],"total":2,"page":1,"size":100,"pages":1}
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/templates
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"items":[{"name":"aws-s3","title":"AWS S3","pub_date":"2025-01-01T00:00:00Z","description":"AWS S3 Storage","short_description":"","schema_version":1,"version":"HEAD","input":{"$defs":{"ApoloSecret":{"properties":{"key":{"title":"Key","type":"string"}},"required":["key"],"title":"ApoloSecret","type":"object","x-description":"Apolo Secret Configuration.","x-is-advanced-field":false,"x-meta-type":"inline","x-title":"Secret","x-type":"ApoloSecret"},"S3Params":{"properties":{"port":{"title":"Port","type":"integer"},"host":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Host"},"bucket":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Bucket"},"access_key":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Access Key"},"secret_key":{"anyOf":[{"$ref":"#/$defs/ApoloSecret"},{"type":"null"}],"default":null}},"required":["port"],"title":"S3Params","type":"object"}},"properties":{"s3":{"$ref":"#/$defs/S3Params"}},"required":["s3"],"title":"AwsS3Input","type":"object"},"output":{"$defs":{"ApoloSecret":{"properties":{"key":{"title":"Key","type":"string"}},"required":["key"],"title":"ApoloSecret","type":"object","x-description":"Apolo Secret Configuration.","x-is-advanced-field":false,"x-meta-type":"inline","x-title":"Secret","x-type":"ApoloSecret"},"S3Params":{"properties":{"port":{"title":"Port","type":"integer"},"host":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Host"},"bucket":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Bucket"},"access_key":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Access Key"},"secret_key":{"anyOf":[{"$ref":"#/$defs/ApoloSecret"},{"type":"null"}],"default":null}},"required":["port"],"title":"S3Params","type":"object"}},"properties":{"s3":{"$ref":"#/$defs/S3Params"}},"required":["s3"],"title":"AwsS3Output","type":"object"},"tags":[],"git_url":"","helm_path":"helm","type":"appless","logo":"","changelog":"","assets":[],"docum
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/api/v1/users/regression-67p1t5y1i1/permissions?uri=blob:
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
[{"uri": "blob://default/regression-org-0myyg5phwb91", "action": "manage"}]
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/admin/v1/users/regression-67p1t5y1i1?include=clusters&include=system_role
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"name": "regression-67p1t5y1i1", "email": "regression-67p1t5y1i1@apolo.us", "first_name": null, "last_name": null, "created_at": "2025-10-11T01:33:23.090098+00:00", "terms_accepted": true, "clusters": [{"cluster_name": "default", "role": "admin", "org_name": "regression-org-0myyg5phwb91", "balance": {"spent_credits": "0"}}]}
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/admin/v1/users/regression-67p1t5y1i1?include=orgs
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"name": "regression-67p1t5y1i1", "email": "regression-67p1t5y1i1@apolo.us", "first_name": null, "last_name": null, "created_at": "2025-10-11T01:33:23.090098+00:00", "terms_accepted": true, "orgs": [{"org_name": "regression-org-0myyg5phwb91", "role": "admin", "balance": {"spent_credits": "0.15"}}]}
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/templates/tags
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
["AI","Agent","Apache","Apolo","Apolo Files","BI","Big data","Bundle","Business Intelligence","CLI","Chat","Container","Container registry","Data","Data processing","DeepSeek","Development","Diffusion","Dify","DockerHub","Document Processing","EDA","ELT","ETL","Easy Deploy","Embeddings","GPT","GptOSS","Graph","Hugging Face","IDE","Image generation","Inference","Jupyter","Knowledge Graph","LLM","LLMops","LLaMA","LightRAG","MLOps","Meta","Mistral","NLP","Notebooks","OpenAI","PostgreSQL","Postgres","RAG","RDBMS","Shell","Spark","Stable Diffusion","Storage","Superset","Text","VSCode","Vector Search","Vector search","Vector store","Visualization","Weaviate","experiment tracking","mlflow","model registry","vLLM"]
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Waiting for spinner
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/templates?page=1&size=50
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"items":[{"name":"aws-s3","title":"AWS S3","pub_date":"2025-01-01T00:00:00Z","description":"AWS S3 Storage","short_description":"","schema_version":1,"version":"HEAD","input":{"$defs":{"ApoloSecret":{"properties":{"key":{"title":"Key","type":"string"}},"required":["key"],"title":"ApoloSecret","type":"object","x-description":"Apolo Secret Configuration.","x-is-advanced-field":false,"x-meta-type":"inline","x-title":"Secret","x-type":"ApoloSecret"},"S3Params":{"properties":{"port":{"title":"Port","type":"integer"},"host":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Host"},"bucket":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Bucket"},"access_key":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Access Key"},"secret_key":{"anyOf":[{"$ref":"#/$defs/ApoloSecret"},{"type":"null"}],"default":null}},"required":["port"],"title":"S3Params","type":"object"}},"properties":{"s3":{"$ref":"#/$defs/S3Params"}},"required":["s3"],"title":"AwsS3Input","type":"object"},"output":{"$defs":{"ApoloSecret":{"properties":{"key":{"title":"Key","type":"string"}},"required":["key"],"title":"ApoloSecret","type":"object","x-description":"Apolo Secret Configuration.","x-is-advanced-field":false,"x-meta-type":"inline","x-title":"Secret","x-type":"ApoloSecret"},"S3Params":{"properties":{"port":{"title":"Port","type":"integer"},"host":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Host"},"bucket":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Bucket"},"access_key":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Access Key"},"secret_key":{"anyOf":[{"$ref":"#/$defs/ApoloSecret"},{"type":"null"}],"default":null}},"required":["port"],"title":"S3Params","type":"object"}},"properties":{"s3":{"$ref":"#/$defs/S3Params"}},"required":["s3"],"title":"AwsS3Output","type":"object"},"tags":[],"git_url":"","helm_path":"helm","type":"appless","logo":"","changelog":"","assets":[],"docum
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/templates?page=1&size=50
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"items":[{"name":"aws-s3","title":"AWS S3","pub_date":"2025-01-01T00:00:00Z","description":"AWS S3 Storage","short_description":"","schema_version":1,"version":"HEAD","input":{"$defs":{"ApoloSecret":{"properties":{"key":{"title":"Key","type":"string"}},"required":["key"],"title":"ApoloSecret","type":"object","x-description":"Apolo Secret Configuration.","x-is-advanced-field":false,"x-meta-type":"inline","x-title":"Secret","x-type":"ApoloSecret"},"S3Params":{"properties":{"port":{"title":"Port","type":"integer"},"host":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Host"},"bucket":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Bucket"},"access_key":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Access Key"},"secret_key":{"anyOf":[{"$ref":"#/$defs/ApoloSecret"},{"type":"null"}],"default":null}},"required":["port"],"title":"S3Params","type":"object"}},"properties":{"s3":{"$ref":"#/$defs/S3Params"}},"required":["s3"],"title":"AwsS3Input","type":"object"},"output":{"$defs":{"ApoloSecret":{"properties":{"key":{"title":"Key","type":"string"}},"required":["key"],"title":"ApoloSecret","type":"object","x-description":"Apolo Secret Configuration.","x-is-advanced-field":false,"x-meta-type":"inline","x-title":"Secret","x-type":"ApoloSecret"},"S3Params":{"properties":{"port":{"title":"Port","type":"integer"},"host":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Host"},"bucket":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Bucket"},"access_key":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Access Key"},"secret_key":{"anyOf":[{"$ref":"#/$defs/ApoloSecret"},{"type":"null"}],"default":null}},"required":["port"],"title":"S3Params","type":"object"}},"properties":{"s3":{"$ref":"#/$defs/S3Params"}},"required":["s3"],"title":"AwsS3Output","type":"object"},"tags":[],"git_url":"","helm_path":"helm","type":"appless","logo":"","changelog":"","assets":[],"docum
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Timeout error for spinner
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Click Continue button
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_click_continue_button_success_b09cb0.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify Apps page displayed
INFO     [🎭 Playwright]:base_page.py:16 <AppsPage>: Check if page loaded
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify Apps page displayed
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_page_displayed_success_a4db6d.png
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Login via UI
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_login_success_827bb0.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify PostgreSQL app container displayed on the main page
INFO     [🎭 Playwright]:base_page.py:16 <MainPage>: Verify app container PostgreSQL displayed
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-0myyg5phwb91&project=regression-proj-9gs75udp89&cluster=default&size=100
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"items":[{"id":"c0472191-d551-4c81-b880-27f8a05dd285","name":"regression-org-0myyg5phwb91-regression-proj--c0472191","created_at":"2025-10-11T01:56:35.783085Z","updated_at":"2025-10-11T01:57:37.485630Z","creator":"regression-67p1t5y1i1","display_name":"Shell-regression-cgcnxukj","template_name":"shell","template_version":"v25.8.0","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"healthy","app_type":"mlops","endpoints":[{"path":"$.app_url.external_url.host","friendly_name":"App Url","url":"https://shell--c0472191d5514c81b88027f8a05dd285.apps.dev.apolo.us"}]},{"id":"b5d9777f-9043-4a25-83ee-c8be2c336f84","name":"regression-org-0myyg5phwb91-regression-proj--b5d9777f","created_at":"2025-10-11T01:50:52.179617Z","updated_at":"2025-10-11T01:59:08.472328Z","creator":"regression-67p1t5y1i1","display_name":"PostgreSQL-regression-jym8a6mh","template_name":"postgres","template_version":"v25.9.1","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"uninstalled","app_type":"workflow","endpoints":[]}],"total":2,"page":1,"size":100,"pages":1}
INFO     [🎭 Playwright]:base_page.py:16 <MainPage>: Scroll to PostgreSQL container...
INFO     [🎭 Playwright]:base_page.py:16 <MainPage>: Scroll to PostgreSQL container...
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-0myyg5phwb91&project=regression-proj-9gs75udp89&cluster=default&size=100
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"items":[{"id":"c0472191-d551-4c81-b880-27f8a05dd285","name":"regression-org-0myyg5phwb91-regression-proj--c0472191","created_at":"2025-10-11T01:56:35.783085Z","updated_at":"2025-10-11T01:57:37.485630Z","creator":"regression-67p1t5y1i1","display_name":"Shell-regression-cgcnxukj","template_name":"shell","template_version":"v25.8.0","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"healthy","app_type":"mlops","endpoints":[{"path":"$.app_url.external_url.host","friendly_name":"App Url","url":"https://shell--c0472191d5514c81b88027f8a05dd285.apps.dev.apolo.us"}]},{"id":"b5d9777f-9043-4a25-83ee-c8be2c336f84","name":"regression-org-0myyg5phwb91-regression-proj--b5d9777f","created_at":"2025-10-11T01:50:52.179617Z","updated_at":"2025-10-11T01:59:08.472328Z","creator":"regression-67p1t5y1i1","display_name":"PostgreSQL-regression-jym8a6mh","template_name":"postgres","template_version":"v25.9.1","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"uninstalled","app_type":"workflow","endpoints":[]}],"total":2,"page":1,"size":100,"pages":1}
INFO     [🎭 Playwright]:base_page.py:16 <MainPage>: Scroll to PostgreSQL container...
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-0myyg5phwb91&project=regression-proj-9gs75udp89&cluster=default&size=100
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"items":[{"id":"c0472191-d551-4c81-b880-27f8a05dd285","name":"regression-org-0myyg5phwb91-regression-proj--c0472191","created_at":"2025-10-11T01:56:35.783085Z","updated_at":"2025-10-11T01:57:37.485630Z","creator":"regression-67p1t5y1i1","display_name":"Shell-regression-cgcnxukj","template_name":"shell","template_version":"v25.8.0","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"healthy","app_type":"mlops","endpoints":[{"path":"$.app_url.external_url.host","friendly_name":"App Url","url":"https://shell--c0472191d5514c81b88027f8a05dd285.apps.dev.apolo.us"}]},{"id":"b5d9777f-9043-4a25-83ee-c8be2c336f84","name":"regression-org-0myyg5phwb91-regression-proj--b5d9777f","created_at":"2025-10-11T01:50:52.179617Z","updated_at":"2025-10-11T01:59:08.472328Z","creator":"regression-67p1t5y1i1","display_name":"PostgreSQL-regression-jym8a6mh","template_name":"postgres","template_version":"v25.9.1","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"uninstalled","app_type":"workflow","endpoints":[]}],"total":2,"page":1,"size":100,"pages":1}
INFO     [🎭 Playwright]:base_page.py:16 <MainPage>: Scroll to PostgreSQL container...
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify PostgreSQL app container displayed on the main page
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_postgres_container_displayed_success_fd3ecc.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Click Install button on the PostgreSQL container
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v1/cluster/default/org/regression-org-0myyg5phwb91/project/regression-proj-9gs75udp89/templates/postgres
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
[{"name":"postgres","title":"PostgreSQL","pub_date":"2025-10-09T15:29:27+03:00","description":"Crunchy PostgreSQL is a scalable, production-grade relational database service\ndesigned for high availability, performance, and flexibility.\\n\nThis managed application includes built-in support for automated backups,\nreplication, and failover to ensure data resilience and minimal downtime.\\n\nIt comes preconfigured with popular extensions like pgvector for AI and machine learning workloads,\nas well as enhanced observability, tuning options,\nand robust security features—making it ideal for modern, data-intensive applications.\n","short_description":"Deploy PostgreSQL cluster on Apolo platform","schema_version":1,"version":"apolo","input":{"$defs":{"ApoloSecret":{"properties":{"key":{"title":"Key","type":"string"}},"required":["key"],"title":"ApoloSecret","type":"object","x-description":"Apolo Secret Configuration.","x-is-advanced-field":false,"x-meta-type":"inline","x-title":"Secret","x-type":"ApoloSecret"},"Bucket":{"properties":{"id":{"description":"The bucket ID.","title":"Bucket ID","type":"string"},"owner":{"description":"The owner of the bucket.","title":"Bucket owner","type":"string"},"details":{"additionalProperties":{"type":"string"},"description":"The details of the bucket.","title":"Bucket details","type":"object"},"credentials":{"description":"The credentials of the bucket.","items":{"anyOf":[{"$ref":"#/$defs/S3BucketCredentials"},{"$ref":"#/$defs/MinioBucketCredentials"},{"$ref":"#/$defs/GCPBucketCredentials"}]},"title":"Bucket credentials","type":"array"},"bucket_provider":{"$ref":"#/$defs/BucketProvider","description":"The provider of the bucket.","title":"Bucket provider"}},"required":["id","owner","bucket_provider"],"title":"Bucket","type":"object","x-description":"Configuration for Bucket.","x-is-advanced-field":false,"x-meta-type":"dynamic","x-title":"Bucket","x-type":"Bucket"},"BucketProvider":{"enum":["AWS","MINIO","GCP","AZURE","OPEN_STACK"],"ti
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Click Install button on the PostgreSQL container
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_postgres_container_click_install_btn_success_ded15f.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify that Postgres install page displayed
INFO     [🎭 Playwright]:base_page.py:16 <PostgresInstallPage>: Check if page loaded
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify that Postgres install page displayed
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_page_displayed_success_822121.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Click Import config button
INFO     [🎭 Playwright]:base_page.py:16 <PostgresInstallPage>: Click Import config button
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Click Import config button
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_click_import_config_btn_success_b0013a.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify Import app config popup displayed
INFO     [🎭 Playwright]:base_page.py:16 <ImportAppConfigPopup>: Check if popup loaded
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify Import app config popup displayed
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_popup_displayed_success_a65645.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Get PostgreSQL app import config file path
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Get PostgreSQL app import config file path
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Import yaml config
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Import yaml config
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_import_yaml_config_success_2285a1.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Click Apply config button
INFO     [🎭 Playwright]:base_page.py:16 <ImportAppConfigPopup>: Click Apply config button
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Click Apply config button
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_click_apply_config_btn_success_5fec75.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Wait for Import app config popup disappear
INFO     [🎭 Playwright]:base_page.py:16 <ImportAppConfigPopup>: Wait for Import App Configuration popup to disappear
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Wait for Import app config popup disappear
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_wait_to_disappear_success_b950da.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify that Postgres install page displayed
INFO     [🎭 Playwright]:base_page.py:16 <PostgresInstallPage>: Check if page loaded
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify that Postgres install page displayed
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_page_displayed_success_3c6ce9.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify Resource preset value
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify Resource preset value
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_resource_preset_value_success_16fa29.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify Postgres replicas count value
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify Postgres replicas count value
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_postgres_replicas_value_success_907bac.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify that Postgres user name value
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify that Postgres user name value
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_postgres_username_value_success_c85f8b.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify Postgres User Database name value
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify Postgres User Database name value
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_postgres_user_db_name_value_success_11b56a.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify PG Bouncer Resource preset value
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify PG Bouncer Resource preset value
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify PG Bouncer replicas count value
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify PG Bouncer replicas count value
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_pg_bouncer_replicas_count_success_4c1c18.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify Postgres Display name value
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify Postgres Display name value
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_postgres_display_name_value_success_1bc883.png
INFO     [📘TEST_INFO]:reporting.py:92 ✅ TEST completed: Import PostgreSQL app config via UI
INFO     [📘TEST_INFO]:reporting.py:98 ------------------------------------------------------------
INFO     [📘TEST_INFO]:reporting.py:155 ============================================================
INFO     [📘TEST_INFO]:reporting.py:156 📊 SUITE SUMMARY: 17 passed, 0 failed
INFO     [📘TEST_INFO]:reporting.py:159 ============================================================
INFO     [🌐API_helper]:api_helper.py:54 GET https://api.dev.apolo.us/apis/admin/v1/orgs
INFO     [🌐API_helper]:api_helper.py:175 Status: 200. Response: [{'name': 'regression-org-0myyg5phwb91', 'balance': {'credits': '499.2899901013333333333333334', 'spent_credits': '0.7100098986666666666666666666'}, 'user_default_credits': None, 'notification_intervals': {'balance_projection_seconds': [604800, 259200, 86400], 'balance_amount': [0], 'balance_depletion_seconds': [86400, 604800]}}]
INFO     [🔧TEST CONFIG]:conftest.py:291 Cleaning up 1 organisations
INFO     [🌐API_helper]:api_helper.py:54 GET https://api.dev.apolo.us/apis/admin/v1/clusters/default/orgs/regression-org-0myyg5phwb91/projects
INFO     [🌐API_helper]:api_helper.py:182 Status: 200. Response: [{'name': 'regression-proj-9gs75udp89', 'cluster_name': 'default', 'org_name': 'regression-org-0myyg5phwb91', 'is_default': False, 'default_role': 'reader', 'has_virtual_kube': False}]
INFO     [🔧TEST CONFIG]:conftest.py:308 Cleaning up 1 projects
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-0myyg5phwb91&project=regression-proj-9gs75udp89&cluster=default&size=100
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"items":[{"id":"c0472191-d551-4c81-b880-27f8a05dd285","name":"regression-org-0myyg5phwb91-regression-proj--c0472191","created_at":"2025-10-11T01:56:35.783085Z","updated_at":"2025-10-11T01:57:37.485630Z","creator":"regression-67p1t5y1i1","display_name":"Shell-regression-cgcnxukj","template_name":"shell","template_version":"v25.8.0","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"healthy","app_type":"mlops","endpoints":[{"path":"$.app_url.external_url.host","friendly_name":"App Url","url":"https://shell--c0472191d5514c81b88027f8a05dd285.apps.dev.apolo.us"}]},{"id":"b5d9777f-9043-4a25-83ee-c8be2c336f84","name":"regression-org-0myyg5phwb91-regression-proj--b5d9777f","created_at":"2025-10-11T01:50:52.179617Z","updated_at":"2025-10-11T01:59:08.472328Z","creator":"regression-67p1t5y1i1","display_name":"PostgreSQL-regression-jym8a6mh","template_name":"postgres","template_version":"v25.9.1","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"uninstalled","app_type":"workflow","endpoints":[]}],"total":2,"page":1,"size":100,"pages":1}
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-0myyg5phwb91&project=regression-proj-9gs75udp89&cluster=default&size=100
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"items":[{"id":"c0472191-d551-4c81-b880-27f8a05dd285","name":"regression-org-0myyg5phwb91-regression-proj--c0472191","created_at":"2025-10-11T01:56:35.783085Z","updated_at":"2025-10-11T02:01:37.453503Z","creator":"regression-67p1t5y1i1","display_name":"Shell-regression-cgcnxukj","template_name":"shell","template_version":"v25.8.0","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"progressing","app_type":"mlops","endpoints":[{"path":"$.app_url.external_url.host","friendly_name":"App Url","url":"https://shell--c0472191d5514c81b88027f8a05dd285.apps.dev.apolo.us"}]},{"id":"b5d9777f-9043-4a25-83ee-c8be2c336f84","name":"regression-org-0myyg5phwb91-regression-proj--b5d9777f","created_at":"2025-10-11T01:50:52.179617Z","updated_at":"2025-10-11T02:01:36.764903Z","creator":"regression-67p1t5y1i1","display_name":"PostgreSQL-regression-jym8a6mh","template_name":"postgres","template_version":"v25.9.1","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"uninstalling","app_type":"workflow","endpoints":[]}],"total":2,"page":1,"size":100,"pages":1}
INFO     [🌐API_helper]:api_helper.py:196 Delete project response: <ClientResponse(https://api.dev.apolo.us/apis/admin/v1/clusters/default/orgs/regression-org-0myyg5phwb91/projects/regression-proj-9gs75udp89) [204 No Content]>
<CIMultiDictProxy('Access-Control-Allow-Credentials': 'true', 'Date': 'Sat, 11 Oct 2025 02:02:06 GMT', 'Server': 'Python/3.13 aiohttp/3.12.15', 'Vary': 'Origin', 'x-service-version': 'platform-admin/0.0.0.post1.dev0+4cdab15', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000')>

INFO     [🔧TEST CONFIG]:conftest.py:314 Deleted project: regression-proj-9gs75udp89
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-0myyg5phwb91&project=regression-proj-9gs75udp89&cluster=default&size=100
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"items":[{"id":"c0472191-d551-4c81-b880-27f8a05dd285","name":"regression-org-0myyg5phwb91-regression-proj--c0472191","created_at":"2025-10-11T01:56:35.783085Z","updated_at":"2025-10-11T02:01:37.453503Z","creator":"regression-67p1t5y1i1","display_name":"Shell-regression-cgcnxukj","template_name":"shell","template_version":"v25.8.0","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"progressing","app_type":"mlops","endpoints":[{"path":"$.app_url.external_url.host","friendly_name":"App Url","url":"https://shell--c0472191d5514c81b88027f8a05dd285.apps.dev.apolo.us"}]},{"id":"b5d9777f-9043-4a25-83ee-c8be2c336f84","name":"regression-org-0myyg5phwb91-regression-proj--b5d9777f","created_at":"2025-10-11T01:50:52.179617Z","updated_at":"2025-10-11T02:01:36.764903Z","creator":"regression-67p1t5y1i1","display_name":"PostgreSQL-regression-jym8a6mh","template_name":"postgres","template_version":"v25.9.1","project_name":"regression-proj-9gs75udp89","org_name":"regression-org-0myyg5phwb91","cluster_name":"default","namespace":"platform--regression-or--regression-p--e41b9d14a226024398fd8eb5","state":"uninstalling","app_type":"workflow","endpoints":[]}],"total":2,"page":1,"size":100,"pages":1}
INFO     [🌐API_helper]:api_helper.py:189 Delete organization response: <ClientResponse(https://api.dev.apolo.us/apis/admin/v1/orgs/regression-org-0myyg5phwb91) [200 OK]>
<CIMultiDictProxy('Access-Control-Allow-Credentials': 'true', 'Content-Length': '329', 'Content-Type': 'application/json; charset=utf-8', 'Date': 'Sat, 11 Oct 2025 02:02:06 GMT', 'Server': 'Python/3.13 aiohttp/3.12.15', 'Vary': 'Origin', 'x-service-version': 'platform-admin/0.0.0.post1.dev0+4cdab15', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000')>

INFO     [🔧TEST CONFIG]:conftest.py:327 Deleted organisation: regression-org-0myyg5phwb91
INFO     [🔧TEST CONFIG]:conftest.py:332 Closing all browser sessions
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 401] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-0myyg5phwb91&project=regression-proj-9gs75udp89&cluster=default&size=100
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"detail":{"missing":[{"uri":"app://default/regression-org-0myyg5phwb91/regression-proj-9gs75udp89","action":"read"}]}}
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 401] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-0myyg5phwb91&project=regression-proj-9gs75udp89&cluster=default&size=100
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"detail":{"missing":[{"uri":"app://default/regression-org-0myyg5phwb91/regression-proj-9gs75udp89","action":"read"}]}}
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 401] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-0myyg5phwb91&project=regression-proj-9gs75udp89&cluster=default&size=100
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"detail":{"missing":[{"uri":"app://default/regression-org-0myyg5phwb91/regression-proj-9gs75udp89","action":"read"}]}}
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 401] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-0myyg5phwb91&project=regression-proj-9gs75udp89&cluster=default&size=100
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"detail":{"missing":[{"uri":"app://default/regression-org-0myyg5phwb91/regression-proj-9gs75udp89","action":"read"}]}}
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:438 [HTTP 401] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-0myyg5phwb91&project=regression-proj-9gs75udp89&cluster=default&size=100
Request Body (first 2000 chars):
<not available>
Response Body (first 2000 chars):
{"detail":{"missing":[{"uri":"app://default/regression-org-0myyg5phwb91/regression-proj-9gs75udp89","action":"read"}]}}
WARNING  [🔧TEST CONFIG]:conftest.py:362 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:348 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:355 Failed to close context: 
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed