{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Product defects","children":[{"name":"AssertionError: [AssertionError] during step: Update user role on a project via CLI\nMessage:  Expected: ERROR: Illegal argument(s) (Last project admin cannot be demoted), got: Your root certificates are out of date.\nYou are using certifi 2025.7.14, however 2025.8.3 is available.\nPlease consider upgrading certifi package, e.g.:\n    python -m pip install --upgrade certifi\nor\n    conda update certifi\n\nYou are using apolo-extras tool 24.10.0, however 25.8.0 is available.\nERROR: Illegal argument(s) (Last project admin cannot be demoted)","children":[{"name":"Admin demote himself to Manager in project via CLI","uid":"4bf1b42d95add80a","parentUid":"e99fd585af277dcd69ee7eab786d2445","status":"failed","time":{"start":1756431938180,"stop":1756431958322,"duration":20142},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":["asyncio"]}],"uid":"e99fd585af277dcd69ee7eab786d2445"},{"name":"AssertionError: [AssertionError] during step: Remove user from project via CLI\nMessage:  Expected: ERROR: Illegal argument(s) (Last project admin cannot be removed), got: Your root certificates are out of date.\nYou are using certifi 2025.7.14, however 2025.8.3 is available.\nPlease consider upgrading certifi package, e.g.:\n    python -m pip install --upgrade certifi\nor\n    conda update certifi\n\nYou are using apolo-extras tool 24.10.0, however 25.8.0 is available.\nERROR: Illegal argument(s) (Last project admin cannot be removed)","children":[{"name":"Admin removes himself from project via CLI","uid":"c27a513f3e94f071","parentUid":"479dc39cce91958685ded324dcf8bb44","status":"failed","time":{"start":1756433195352,"stop":1756433245532,"duration":50180},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":["asyncio"]}],"uid":"479dc39cce91958685ded324dcf8bb44"},{"name":"AssertionError: [AssertionError] during step: Add user to organization via CLI\nMessage: ERROR: Not enough permissions ({\"missing\": [{\"uri\": \"org://regression-org-2xj19omfjdp5/users\", \"action\": \"write\"}]})","children":[{"name":"Manager removes Admin from org via **CLI**","uid":"6459ec7494cc3a2d","parentUid":"112679edc812f2b283a8a73e86a8c253","status":"failed","time":{"start":1756434433242,"stop":1756434477829,"duration":44587},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":["asyncio"]}],"uid":"112679edc812f2b283a8a73e86a8c253"},{"name":"AssertionError: [AssertionError] during step: Add user not in organization to project via CLI\nMessage: Expected: \nERROR: User 'regression-org-1yhdvxedsqla/regression-q61pshs8fu' not found in cluster 'default' \nbut got \nYour root certificates are out of date.\nYou are using certifi 2025.7.14, however 2025.8.3 is available.\nPlease consider upgrading certifi package, e.g.:\n    python -m pip install --upgrade certifi\nor\n    conda update certifi\n\nYou are using apolo-extras tool 24.10.0, however 25.8.0 is available.\nERROR: User 'regression-org-1yhdvxedsqla/regression-q61pshs8fu' not found in cluster 'default'","children":[{"name":"Add user not in organization to project via CLI","uid":"e6d96983fb442586","parentUid":"3f63a0e73c19f9ce5acd45493828db98","status":"failed","time":{"start":1756435734889,"stop":1756435773997,"duration":39108},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":false,"parameters":[],"tags":["asyncio"]}],"uid":"3f63a0e73c19f9ce5acd45493828db98"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}]}